explorer_docker_network_name: explorernet

beacon_explorer_container_name: explorer
execution_explorer_container_name: blockscout

explorer_memory: 9000m
beacon_explorer_image_name: "parithoshj/beacon-explorer:print-chain-id"
execution_explorer_image_name: "skylenet/blockscout:v4.0.0-beta"

explorer_first_block: 14651000
explorer_ip_address: "164.92.169.47"

explorer_postgres_container_name: postgres
explorer_postgres_image_name: "postgres:12.0"
explorer_postgres_memory: 9000m

explorer_postgres_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/merge-devnets/merge-devnet-3/explorer-postgres') }}"

explorer_postgres_host_dir: "{{home_dir}}/explorer_postgres_data"
explorer_postgres_volumes:
  - "{{explorer_postgres_host_dir}}:/postgresql/data"
explorer_postgres_start_args: "-i -h 172.1.1.100"

explorer_postgres_init_volumes:
  - "{{explorer_host_dir}}:/src"

explorer_postgres_init_args: >
  psql -f /src/tables.sql -d db -h 172.1.1.100 -p 5432 -U postgres


explorer_host_dir: "{{home_dir}}/explorer_data"

execution_explorer_volumes:
  - "{{explorer_host_dir}}:/data"
  - "{{testnet_dir}}:/custom_config_data"

beacon_explorer_volumes:
  - "{{explorer_host_dir}}:/data"
  - "{{testnet_dir}}/config.yaml:/app/eth2_config.yaml"

beacon_explorer_start_args: "./explorer --config=/data/config.yaml"

execution_explorer_start_args: "sh -c \"echo $DATABASE_URL &&
                                 mix do ecto.create, ecto.migrate &&
                                 exec mix phx.server\" "

explorer_stats_container_name: explorerstats

explorer_stats_volumes:
  - "{{explorer_host_dir}}:/data"

explorer_stats_start_args: "./statistics --config=/data/config.yaml"

explorer_beacon_extra_args: "--slots-per-archive-point=64"
