eth1_client_name: besu
eth1_image_name: hyperledger/besu:develop-amd64
execution_endpoint: http://127.0.0.1:{{eth1_engine_port}}

eth1_memory: 5000M
eth1_kernel_memory: 5500M

eth1_github_external_user_pubkeys:
  - garyschulte
  - jflo

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

eth1_env:
  JDWP_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  NATIVE_MEMORY_OPTS: "-XX:NativeMemoryTracking=detail -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics"

eth1_start_args: >
  --data-path="/eth1data/data"
  --network=kiln
  --max-peers=100
  --rpc-http-enabled=true --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{eth1_rpc_port}}
  --engine-rpc-enabled=true
  --engine-rpc-port={{eth1_engine_port}}
  --engine-host-allowlist="*"
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled=true --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-ws-host=0.0.0.0
  --host-allowlist="*"
  --p2p-enabled=true
  --metrics-enabled
  --metrics-host=0.0.0.0
  --metrics-port={{eth1_metrics_port}}
  --p2p-enabled=true
  --miner-coinbase="{{fee_recipient}}"
  --p2p-host={{ansible_host}}
  --engine-jwt-enabled
  --engine-jwt-secret=/jwtsecret
  {% if (eth1_bootnode_enode is defined) and bootnode_enrs %}
  --bootnodes="{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"
