version: "3.4"
services:
  besu:
    image: suburbandad/besu:kintsugi-v3
    container_name: besu
    volumes:
      - ./execution_data:/execution_data
      - ../../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --data-path="/execution_data"
      --genesis-file="/custom_config_data/besu_genesis.json"
      --network-id=$NETWORK_ID
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --p2p-enabled=true
      --Xmerge-support=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --bootnodes=$ENODE
    network_mode: host
