eth1_client_name: besu
eth1_image_name: hyperledger/besu:develop
execution_endpoint: http://127.0.0.1:{{eth1_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port_no_auth}}"

eth1_memory: 5000M
eth1_kernel_memory: 5500M

eth1_github_external_user_pubkeys:
  - garyschulte
  - jflo

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"


eth1_start_args: >
  --data-path="/eth1data/data"
  --genesis-file="/networkdata/besu_genesis.json"
  --network-id={{chainID}}
  --rpc-http-enabled=true --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{eth1_rpc_port}}
  --engine-rpc-http-port={{eth1_engine_port_no_auth}}
  --engine-host-allowlist="*"
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled=true --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE
  --rpc-ws-host=0.0.0.0
  --rpc-ws-port={{eth1_ws_rpc_port}}
  --host-allowlist="*"
  --p2p-enabled=true
  --Xmerge-support=true
  --miner-coinbase="0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73"
  --p2p-host={{ansible_host}}
  --sync-mode=FAST
  --data-storage-format="BONSAI"
  --engine-jwt-enabled
  --engine-jwt-secret=/jwtsecret
  {% if (eth1_bootnode_enode is defined) and bootnode_enrs %}
  --bootnodes="{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"
