##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8546
# lighthouse uses this
execution_engine_endpoint: http://127.0.0.1:8545

eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: merge-devnet-4
chainID: 1337752
terminal_total_difficulty: "5000000000"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-KG4QL7_0L_f8Ug9ZHJt03upYa0PdpmEl5wInTejEsKE5X8MYbBU0FOuSAafsQxbQiWsY3326s41Kj-X28lYe_91AgIDhGV0aDKQ7zvXpGEABXAKAAAAAAAAAIJpZIJ2NIJpcIRA44B-iXNlY3AyNTZrMaEDWxFbrX3tif8zq7Q8fTqk00dAU3q6az5S9VqeDZ2rx9-DdGNwgiMog3VkcIIjKA"
  - "enr:-LK4QDHftmIXxcbqaI4qGj0lcyM66-OYVFP-neUNLqhaDO8qFpRU6uRQc4gsUrIHycXZVTqyB8gUoa13trsVFj_pLcQBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDvO9ekYQAFcAoAAAAAAAAAgmlkgnY0gmlwhKRcwTOJc2VjcDI1NmsxoQLYzPfRQpYidSbLk3dYmMkuVILl7h_ZXzKWcWUtpwHFjYN0Y3CCIyiDdWRwgiMo"
  - "enr:-MK4QHnkHjBWGHeleYfnw05TTxMFnFQoJpKYd7bg3M_8RMXZfzhYK3aXdz5cBX8NZuBFk9lSzqlh4hXiB_nRbOGI-BuGAX8HlAT3h2F0dG5ldHOI__________-EZXRoMpDvO9ekYQAFcAoAAAAAAAAAgmlkgnY0gmlwhKRczoeJc2VjcDI1NmsxoQJSZ0tu9MINVtKCJDDB5LL9XLNi8PYu8Y6cyyd0gqhtMIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA=="

eth1_bootnode_enode:
  - "enode://77927a49570f079b4b73c4fca0c50206c48d3a22ed175e715fbfaccc08f838813d527b4ba9929a99bc87d53b8e80a63b185a37d9c950d57c227004b8c4e8fec1@164.92.193.6:30303"
  - "enode://6167e29219f7a0d35847a784111e5da1d3d52c074711692fdde7f8077c48943fd875fd2f5cc8b4813e6f35e56071ae3d85beaf6b06d8666fdad019d0be3e70f7@64.227.128.126:30303"
  - "enode://74744416c7fbdf28cb0a2631d8590c10d31f1d09e944e7f54d9dbf5741d088d4e0360e7c897e0527aee0bc9408cfac0edbea8571cc0ca445bd599be537aad262@164.92.206.58:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
thanos_url: "http://thanos.ethdevops.io:19291/api/v1/receive/"
push_metrics_enabled: true

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file
beacon_log_level: info

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 164.92.193.6 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 164.92.193.6 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 4000 -s 161.35.95.49 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 161.35.95.49 -j ACCEPT"